name: Sync Tampermonkey to Firefox Extension

on:
  push:
    paths:
      - 'monkey/swpfl.user.js'
      - '.github/workflows/update-swpfl.yml'
  workflow_dispatch: {}

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare userscript file
        run: |
          cp monkey/swpfl.user.js script.user.js

      - name: Extract and unindent content between markers
        run: |
          sed -n '/\/\/ -- begin --/,/\/\/ -- end --/p' script.user.js \
            | sed '1d;$d' \
            | sed 's/^    //' \
            > firefoxExtInstall/swpfl/swpfl.js

      - name: Replace storage & GM_ APIs
        run: |
          sed -E -i \
            -e "s@localStorage.getItem\(\"([^\"]+)\"\)@await browser.storage.local.get(\"\\1\").then(r=>r[\"\\1\"])@g" \
            -e "s@localStorage.setItem\(\"([^\"]+)\",[ ]*(.+)\)@await browser.storage.local.set({ \"\\1\": \2 })@g" \
            -e "s@localStorage.removeItem\(\"([^\"]+)\"\)@await browser.storage.local.remove(\"\\1\")@g" \
            -e "s@GM_getValue\(\"([^\"]+)\"\)@await browser.storage.local.get(\"\\1\").then(r=>r[\"\\1\"])@g" \
            -e "s@GM_setValue\(\"([^\"]+)\",[ ]*(.+)\)@await browser.storage.local.set({ \"\\1\": \2 })@g" \
            -e "s@GM_deleteValue\(\"([^\"]+)\"\)@await browser.storage.local.remove(\"\\1\")@g" \
            -e "s@GM_addStyle@(function(css){ var s=document.createElement(\"style\"); s.textContent=css; document.head.appendChild(s); })@g" \
            -e "s@GM_download\(([^)]+)\)@browser.downloads.download(\1)@g" \
            firefoxExtInstall/swpfl/swpfl.js

      - name: Sync manifest version
        id: bump_version
        run: |
          version=$(grep -m1 '^// @version' script.user.js | awk '{print $3}')
          echo "Parsed version: $version"
          jq ".version = \"${version}\"" firefoxExtInstall/swpfl/manifest.json > manifest.tmp.json
          mv manifest.tmp.json firefoxExtInstall/swpfl/manifest.json
          echo "version=$version" >> $GITHUB_OUTPUT
          echo '{"current": "'"$version"'"}' | jq . > /version.json


      - name: Package extension folder
        run: |
          cd firefoxExtInstall/swpfl && zip -r ../swpfl.zip ./

      - name: Prepare packages folder
        run: |
          mkdir -p firefoxExtInstall/packages
          mv firefoxExtInstall/swpfl.zip firefoxExtInstall/packages/swpfl-${{ steps.bump_version.outputs.version }}.zip

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: swpfl-extension-${{ steps.bump_version.outputs.version }}
          path: firefoxExtInstall/packages/swpfl-${{ steps.bump_version.outputs.version }}.zip

      - name: Commit packages and changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add firefoxExtInstall/packages/swpfl-${{ steps.bump_version.outputs.version }}.zip firefoxExtInstall/swpfl/swpfl.js firefoxExtInstall/swpfl/manifest.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: sync extension v${{ steps.bump_version.outputs.version }} and package zip"
            git push
          else
            echo "No changes to commit."
          fi