name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch: # allow manual run

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Render app
        run: curl -sSf https://src-backend.onrender.com || echo "Render ping failed"
